### PR TITLE
#6: Added version pom element into FlattenDescriptor

### PR DESCRIPTION
**Pull request by cemo**

### CODE REVIEW

**Comment by cemo** [comment]
any chance to merge?

**Comment by hboutemy** [comment]
I'm not an expert of this plugin, but just on the format of this PR:
1. please explain what you are trying to solve, because this is not obvious
2. please rework the commit, since currently it completely replaces the whole file instead of having a diff on what you really changed (newline issue?)

**Comment by pdubs10** [comment]
Looks like a duplicate of https://github.com/mojohaus/flatten-maven-plugin/pull/4 with indentation changes?

**Comment by cemo** [comment]
Exactly. Closing this issue.

**Pull request closed without merging**
