### PR TITLE
Fix #26: Resolve multi-module projects

### LINKED ISSUE #26: version properties not resolved in imported boms on mvn goal package
I just run a new build of the [oasp/oasp4j](https://github.com/oasp/oasp4j) just executing the `mvn package` goal rather than the `install` goal. This leads to a build error in the [beanmapping module](https://github.com/oasp/oasp4j/blob/develop/modules/beanmapping/pom.xml) as the version for

``` xml
<dependency>
      <groupId>net.sf.m-m-m</groupId>
      <artifactId>mmm-util-entity</artifactId>
</dependency>
```

could not be resolved. The version is managed in the [oasp4j-bom](https://github.com/oasp/oasp4j/blob/develop/bom/pom.xml). It seems that the version property `${mmm.util.version}` could not be resolved running `mvn package`. However, running `mvn install` everything is working.

### PR DESCRIPTION
**Pull request by cboehme**
Adds the projects in the reactor to FlattenModelResolver. This is
necessary for multi-module projects where one module imports another as
a bom as this module may not be available in the local repository.

The changes in this commit rely on MavenSession.getAllProjects() to
return the unconstrained list of projects in the reactor. This is not
the case in Maven versions 3.3.1, 3.3.3 and 3.3.9. A fix has been
submitted (see https://issues.apache.org/jira/browse/MNG-6173). Without
this fix multi-module projects will only build correctly if the all
modules are built. Constraining the list of modules with the -pl
commandl line option would not work.

### CODE REVIEW

**Comment by cboehme** [comment]
Commit ed66f2fcfcd2f8e08f0e3d563cc043dbe4e0587d requires that the flatten-maven-plugin is built with at least Maven 3.5.0-alpha-1 otherwise the integration tests fail.

**Comment by cboehme** [comment]
I have rebased the pull request so that it can be merged without conflicts.

**Comment by khmarbaise** [comment]
Hi would you please so kind to squash the commits into a single commit this makes it easier to merge and having only a single commit which contains the whole fix/improvement.

**Comment by cboehme** [comment]
No problem, I squashed everything into a single commit.

**Comment by khmarbaise** [comment]
Great. Thanks.

**Comment by hohwille** [comment]
@cboehme and @khmarbaise 👍 Thanks for your work! As I wrote I was heavily under water the last months and somehow my github notifications for mojohaus went to nirvana. However, now I am back and we should see to get a release pulled out and I also am in the process of getting through other PRs.

**Comment by hohwille** [comment]
> Commit ed66f2f requires that the flatten-maven-plugin is built with at least Maven 3.5.0-alpha-1 otherwise the integration tests fail.

It is not only about the integration tests. The entire plugin will now not work anymore if you do not have maven 3.5.0-alpha-1 +
In case there is any change we can avoid this, I would heavily suggest to go for that. Maven 3.3 is spread all over. Maven 3.5 is quite fresh and updating all build systems will take time. In the worst case another plugin will stop working with 3.5 due to a new bug then users are entirely locked out.

**Comment by hohwille** [comment]
Raising the requirement from `3.2.1` to `3.5.0` in a microversion bugfix release is IMHO not a good idea. In the future I would considere to have multiple branches and do a version planning for PRs and issues and then only merge to the proper version branch according to some rules of thumb.

**Comment by hohwille** [comment]
BTW: I have tested the plugin with the old `3.2.1` dependency (without caring for ITs) and it is already fixing the bug in regular reactor situations. So thanks again for the fix. I would consider to first pull out a release with the `3.2.1` maven requirement (temporary disable ITs for the release or whatever) and then postpone the "cleanup" with raising to maven `3.5.0` to at least `1.1.0` release of `flatten-maven-plugin`. Any concerns or agreements on this?

**Comment by cboehme** [comment]
@hohwille I have no concerns. Disabling the ITs is probably the easiest solution. I tried to build the `flatten-maven-plugin` with Maven 3.2.1 but that failed because "No mojo definitions were found for plugin ...". I'm not sure if it makes sense to investigate this further.

**Comment by hohwille** [comment]
@cboehme thanks for your feedback. I managed to build it for `3.2.1` with 2 ITs failing.
And also I was right about the implication with maven `3.5.0` and potential bugs:
https://issues.apache.org/jira/browse/MNG-6286

**Comment by hohwille** [comment]
Also we must not use version range for ${maven.version}. It was also used by @khmarbaise for javadoc link URL and that is broken with version range.
My current plan:
* fix that on master
* branch master off to `1.0.x` branch and retrofit there to maven `3.2.1` and pull `1.0.1` release out from there.
* then master is for `1.1.0` and above.
* further PRs can be first assigned to releases via milestones and then merged on the according branch.
* I will add `Contributing.md` to document this and also link general MojoHaus conventions.
* I will add `1.0.x` branch build status as travis icon to `Readme.md`

**Comment by hohwille** [comment]
Please test and vote
https://groups.google.com/forum/#!topic/mojohaus-dev/kZ6SOBCwnSc

**Pull request merged**
