### PR TITLE
Flatten maven plugin 1.1.x

### PR DESCRIPTION
**Pull request by nruzic**
resolveCiFriendliesOnly mode is not perfect currently.
It should interpolate version and parent elements only.
I have discovered that if you have some profiles active during build, flatten-maven-plugin in resolveCiFriendliesOnly mode will interpolate some placeholders in active profiles (e.g. if you use mvn clean install -PsomeProfile).
This is not desirable, at least for me :-)
I have introduced alternative solution for resolving original pom model in FlattenMojo so that no placeholders are resolved except version and parent.
Solution is not perfect, but it can be used as guide for more permanent solution to the problem.
Test case is included which illustrates the problem.

### CODE REVIEW

**Comment by famod** [comment]
`oraclejdk8` problem on Travis should vanish once #106 is merged.

**Comment by hohwille** [comment]
#106 is merged. Restarting the travis build for PRs does not help. Seems all need to merge that back into their forks to update PRs properly.

**Comment by hohwille** [comment]
PR never worked in travis and has merge conflicts. Will it still be maintained (=merged)?

**Comment by hohwille** [comment]
Replaced by PR #114

**Pull request closed without merging**
