### PR TITLE
Add an integration test for #96

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by gnodet** [comment]
@hohwille here is the integration test for #96

**Comment by gnodet** [comment]
The test is failing with maven 3.5.4 because in the written pom, the namespace location has changed from `http://maven.apache.org/xsd/maven-4.0.0.xsd` to `https://maven.apache.org/xsd/maven-4.0.0.xsd`, so the pom equality check fails.
Trying with forcing 3.6.3 for testing...

**Comment by famod** [comment]
I have two suggestions:
- introduce Travis-`matrix` to cover multiple Maven versions (here is an example: https://github.com/vackosar/gitflow-incremental-builder/commit/7e344e8c0ea0af7cc206ddae2a437a6cf7cd85e2#diff-354f30a63fb0907d4ad57269548329e3)
- create _two_ ITs, one for 3.5.4 and one for 3.6+ and control which IT is run via `invoker.maven.version`: http://maven.apache.org/plugins/maven-invoker-plugin/examples/selector-conditions.html

@hohwille & @lasselindqvist WDYT?

**Comment by gnodet** [comment]
On a side note and fwiw, the test does require maven 3.6, but the feature itself does not.  That's only because the test has a copy of the generated flattenned pom which differes on 3.5 and 3.6.  The test could be rewritten for 3.5 if we want, or we could try to make it independant, but that would require 2 maven runs to check that the second run of the plugin does not overwrite the pom that has been generated the first run.

**Comment by hohwille** [comment]
@gnodet awesome. You are fast. Thanks for this contribution 👍 
I will observe if there is another way to deal with this maven version problem...
Could you also simply just change the `.flattened.pom` that you committed to the IT to contain the other namespace?
I do not mind lifting the version to `3.6` but `3.6.3` is quite recent and that change might give us a blind spot for future breaking changes if the plugin accidentally requires `3.6.3+` then.

**Comment by famod** [comment]
@gnodet 
> but that would require 2 maven runs to check that the second run of the plugin does not overwrite the pom that has been generated the first run.

For TravisCI this no problem, see my comment regarding the `matrix` feature. It would simply run multiple builds concurrently, in different containers with different Maven versions.

IMHO, a maven plugin or extension should always be built/tested against not only one single Maven version.

But true, covering this _locally_ is a different story.

**Comment by gnodet** [comment]
@hohwille i moved back to using maven 3.5.4

@famod that's not what i meant.  This very test ensure that the generated pom is not overwritten if nothing has changed.  In the current setup, the source code embeds the flattened pom, so that the integration test runs maven and the test verifies that the generated pom has not been touched.  But the fact that we embed the generated pom makes the test dependant on the maven version (because the generated file is different between 3.5 and 3.6).  In order to get passed this, we'd need the test to: run maven, store the modification date of the generated pom, run maven again, check that the file has not been touched.  I'm not sure how to do that with a simple maven invoker integration test.

**Comment by famod** [comment]
@gnodet Ok, sorry for the confusion!

**Comment by famod** [comment]
Hm, what about a single pom that calls flatten-plugin twice (in two different phases) and in between antrun?

**Comment by gnodet** [comment]
@famod not sure, that sounds a bit complicated. If we want to support both maven versions, i'd rather duplicate the test and use an `invoker.properties` with a correct `invoker.maven.version` in order to make sure both maven versions are supported.  It looks easier to me.

**Pull request merged**
