### PR TITLE
Fix #89 (partially): only resolve parents with version-range

### LINKED ISSUE #89: When using Maven 3.6, a pom that imports a bom in its dependency management from a repository other than Maven Central cannot be flattened
I've encountered a problem with 1.1.0 of the Flatten Maven Plugin when used with Maven 3.6.0 in Spring Boot's build. I've boiled things down to a much simpler example which is available in [this GitHub repository](https://github.com/wilkinsona/flatten-maven-plugin-problem). The README hopefully does a reasonable job of explaining the problem. In a nutshell, when using Maven 3.5.4 the repository configured in the root pom is available to resolve the imported bom and flattening works. When using Maven 3.6.0, the repository configured in the root pom is not available to resolve the imported bom and flattening fails.

Some [initial analysis](https://github.com/spring-projects/spring-boot/issues/16167) would suggest that our use of `${revision}` is important to the problem. If I replace it with a hardcoded version the problem then occurs with both 3.5.4 and 3.6.0. This makes me suspect that either I'm doing something wrong, or there's a bug in the Flatten Maven Plugin. My apologies for opening an issue if it's the former, but a pointer to the correct approach would be much appreciated. If it's the latter, please let me know if there's anything I can do to help to diagnose the problem.

### PR DESCRIPTION
**Pull request by famod**
This will prevent the resolution errors in case the parent element uses a regular version, **not** a version range.

Resolution of version ranges _seems_ to require remote repository access, always!
That is my conclusion after playing around with an empty remote repository list on the `ProjectBuildingRequest` and/or an offline `RepositorySystemSession`.
In both cases, the `parent-with-version-range` integration test fails.
Empty repo list:
```
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for org.codehaus.mojo.flatten.its:parent-with-version-range:0.0.1-SNAPSHOT
[FATAL] Non-resolvable parent POM for org.codehaus.mojo.flatten.its:parent-with-version-range:0.0.1-SNAPSHOT: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.codehaus.mojo.flatten.its:parent-deps:pom:[0,2] and 'parent.relativePath' points at wrong local POM @ 
```
Offline:
```
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for org.codehaus.mojo.flatten.its:parent-with-version-range:0.0.1-SNAPSHOT
[FATAL] Non-resolvable parent POM org.codehaus.mojo.flatten.its:parent-deps:[0,2] for org.codehaus.mojo.flatten.its:parent-with-version-range:0.0.1-SNAPSHOT: org.eclipse.aether.resolution.DependencyResolutionException: Cannot access mrm-maven-plugin (http://localhost:59583) in offline mode and the artifact org.codehaus.mojo.flatten.its:dep:jar:1.1 has not been downloaded from it before. and 'parent.relativePath' points at wrong local POM @ 
```

So to fix this problem also for version ranges, `FlattenModelResolver.addRepository()` methods will probably need to collect all repositories which are then used for the `depencencyResolver.resolveDependencies()` invocation.
This should be addressed in a separate issue/PR.

PS, test coverage: I did not add a new test because for version ranges there is already `parent-with-version-range` and other tests already cover non-version-ranged parents.
Furthermore I really don't know how set up this rather complicated scenario (mutliple remotes etc.).

### CODE REVIEW

**Comment by hohwille** [comment]
```
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
install-jdk.sh 2019-05-02
Expected feature release number in range of 9 to 13, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```
Seems as if travis again has some general errors. All we require is oraclejdk8:
https://github.com/mojohaus/flatten-maven-plugin/blob/master/.travis.yml#L6

**Comment by famod** [comment]
@hohwille Is there anything I can do to help this getting merged and released?

**Comment by famod** [comment]
Build should be fixed once #106 is merged.

**Comment by famod** [comment]
@hohwille All checks have passed. Is there anything blocking this from being merged?
PS: Same question for my other PRs...

**Comment by khmarbaise** [comment]
Merge. Thanks.

**Comment by vinsgithub** [comment]
Hi, good news about successful merge but cannot see any info about an official release that contains this fix. Is there any plan to to do that?
Thank you.

**Comment by nlitterat** [comment]
+1 on @vinsgithub  question

**Comment by famod** [comment]
@vinsgithub & @nlitterat there is an ongoing discussion about a new release: https://github.com/mojohaus/flatten-maven-plugin/issues/125

**Pull request closed without merging**
