### PR TITLE
Added the ability to configure how to handle "version" property.

### PR DESCRIPTION
**Pull request by pdubs10**

### CODE REVIEW

**Comment by pdubs10** [comment]
This allows you to specify resolution strategy for "version" property, which allows a workaround to the underlying issue in https://github.com/mojohaus/flatten-maven-plugin/issues/3 with a pomElements section.

    <configuration>
            <pomElements>
                <version>resolve</version>
            </pomElements>
    </configuration>

**Comment by hohwille** [comment]
Awesome. Thanks for the PR mate!
Should "resolve" then be the default for version and we then would have an offical fix for #3?

**Comment by pdubs10** [comment]
@hohwille Yeah I can't think of a situation where you wouldn't want to resolve variable substitution as a default.

**Comment by hohwille** [comment]
Release is prepared. You are welcome to test and vote:
https://groups.google.com/forum/#!topic/mojohaus-dev/kHVNoyGvK5o

**Pull request merged**
