### PR TITLE
Update Maven to 3.5.0

### PR DESCRIPTION
**Pull request by gnodet**
- Update maven to 3.5.0
- Implement missing ModelResolver method
- Remove unsupported <reports/> tags

### CODE REVIEW

**Review by cstamas — APPROVED** [review]

**Comment by gnodet** [comment]
@slawekjaranowski

**Review by slawekjaranowski — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
does this resolve #330?

**Comment by gnodet** [comment]
> does this resolve #330?

Yes, exactly, it solves the `AbstractMethodError` exception.  I've verified that running 4.0.0-m5 with this patched plugin does indeed work correctly.

**Comment by gnodet** [comment]
@slawekjaranowski I don't have karma on this repo, so feel free to merge.

**Review by cstamas — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
As alway with such change I wonder what next version should be ... should we bump Major?
@gnodet @cstamas @slachiewicz  - what do you think?

**Comment by slachiewicz** [comment]
1.5.0 should be fine

**Pull request merged**
