### PR TITLE
Fix #59: prevent NPE in Eclipse/m2e

### LINKED ISSUE #59: fails in eclipse
https://wiki.eclipse.org/M2E_compatible_maven_plugins

1) any attempt to enable flatten in eclipse:
```
<pluginExecution>
	<pluginExecutionFilter>
		<groupId>org.codehaus.mojo</groupId>
        	<artifactId>flatten-maven-plugin</artifactId>
		<versionRange>[0,)</versionRange>
		<goals>
			<goal>flatten</goal>
		</goals>
	</pluginExecutionFilter>
	<action>
		<execute>
			<runOnIncremental>false</runOnIncremental>
                        <runOnConfiguration>true></runOnConfiguration>
		</execute>
	</action>
</pluginExecution>
```

2) results in plugin error `java.lang.NullPointerException`:
```
Description	Resource	Path	Location	Type
Execution flatten of goal org.codehaus.mojo:flatten-maven-plugin:1.0.1:flatten failed. (org.codehaus.mojo:flatten-maven-plugin:1.0.1:flatten:flatten:package)

org.apache.maven.plugin.PluginExecutionException: Execution flatten of goal org.codehaus.mojo:flatten-maven-plugin:1.0.1:flatten failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.NullPointerException
	at org.codehaus.mojo.flatten.model.resolution.ReactorModelPool.addProjects(ReactorModelPool.java:46)
	at org.codehaus.mojo.flatten.model.resolution.FlattenModelResolver.<init>(FlattenModelResolver.java:70)
	at org.codehaus.mojo.flatten.FlattenMojo.createModelBuildingRequest(FlattenMojo.java:684)
	at org.codehaus.mojo.flatten.FlattenMojo.createFlattenedPom(FlattenMojo.java:447)
	at org.codehaus.mojo.flatten.FlattenMojo.execute(FlattenMojo.java:313)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 31 more

### PR DESCRIPTION
**Pull request by famod**
Fixes #59 by falling back to either regular "projects" or an empty list, eventually.

### CODE REVIEW

**Comment by famod** [comment]
There is a setup problem on travis which someone needs to fix:
```
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
install-jdk.sh 2019-04-29
Expected feature release number in range of 9 to 13, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
Your build has been stopped.
```

**Comment by famod** [comment]
Please note that is based on ac9eddb349691d91ad96188dbf01272b57b07efb (currently `HEAD~1` in `master`) and not df25d03a4d6c06c4de5cfd9f52dfbe72e823e403 (currently `HEAD` in `master`) due to [this issue](https://github.com/mojohaus/flatten-maven-plugin/issues/87#issuecomment-488781161).

**Comment by famod** [comment]
`oraclejdk8` problem on Travis should vanish once #106 is merged.

**Comment by famod** [comment]
> Please note that is based on [ac9eddb](https://github.com/mojohaus/flatten-maven-plugin/commit/ac9eddb349691d91ad96188dbf01272b57b07efb) (currently `HEAD~1` in `master`) and not [df25d03](https://github.com/mojohaus/flatten-maven-plugin/commit/df25d03a4d6c06c4de5cfd9f52dfbe72e823e403) (currently `HEAD` in `master`) due to [this issue](https://github.com/mojohaus/flatten-maven-plugin/issues/87#issuecomment-488781161).

To pull in the travis fix, this is now based in master.

**Comment by khmarbaise** [comment]
Merged.

**Pull request closed without merging**
