### PR TITLE
Fix #140 by separating no-overwritten test into two basing on maven version

### LINKED ISSUE #140: no-overwrite\pom.xml IT fails in some environments
Task: Release from master
Note: Lost my private keys due to data loss, so had to create a new one so the signing keys for the release will differ from the previous.

### PR DESCRIPTION
**Pull request by yangnuoyu**
Fixes #140  @stephaniewang526 @saturnism @elharo

### CODE REVIEW

**Comment by elharo** [comment]
INFO] -------------------------------------------------

[ERROR] The following builds failed:

[ERROR] *  no-overwrite-3.6.2-before/pom.xml

[INFO] -------------------------------------------------

**Comment by stephaniewang526** [comment]
LGTM

**Comment by stephaniewang526** [comment]
@olamy PTAL

**Comment by famod** [comment]
This PR assumes that one uses `mvnw`, but I don't do so. So now I am getting:
```The post-build script did not succeed. Cannot run program "./mvnw": CreateProcess error=193, %1 ist keine zulässige Win32-Anwendung```
The second part is something like this in English:
```%1 is no valid Win32-application```

**Comment by hboutemy** [comment]
@yangnuoyu @stephaniewang526 I don't understand the difference between the 2 ITs: what is different before and after Maven 3.6.3, please?

**Comment by hboutemy** [comment]
ok, I finally found the http vs https xsd url in `.flattened-pom.xml `

ITs made more simple & reliable by using Maven version selection in `invoker.properties` https://maven.apache.org/plugins/maven-invoker-plugin/run-mojo.html#invokerPropertiesFile

**Pull request merged**
